spring.application.name=cadastro-cinema
spring.h2.console.enavled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:cinema
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=
spring.datasource.password=
